title: SoleFresh Каталог
description: "Выберите услуги и добавьте в корзину"

# Отключение Jekyll для статического сайта
plugins: []
theme: none
markdown: kramdown
permalink: pretty

# Разрешить обработку всех нужных файлов
include: [".html", ".css", ".js", ".svg", ".png", ".jpg"]
exclude: ["README.md"]

# Настройки для GitHub Pages
github:
  metadata: true
