title: Sole Fresh - Химчистка обуви
description: "Профессиональная химчистка обуви. Расчет стоимости онлайн"
theme: jekyll-theme-minimal
plugins: []
include: [".html", ".css", ".js", ".jpg", ".png", ".svg"]
exclude: ["README.md"]
